### ISSUE TITLE
.exe opens but nothing happens

### ISSUE THREAD

**Issue by WafffleGod** [peterbn/EDx52display#6]
I downloaded the .Zip and fired up the `EDx52display.exe` but i only get a blank command prompt popping up and closing. I'm sure I missed something, but can't figure out what exactly. I created exceptions in both my firewall and AV, even tried turning them both off. Any ideas?

Cheers

**Comment by peterbn** [comment]
Hi WaffleGod.

Very curious. Could you try to open it through the command line prompt?

It sounds like it crashes on startup, and it might be printing some error information that is lost when the command prompt window closes, but if you manually open a command prompt (`cmd`), navigate to the folder where you unzipped the program, and execute it, then the error message should stay behind when it crashes.

Let me know if you want more detailed instructions on how to do this.

**Comment by WafffleGod** [comment]
Alright, this is what I get when trying to execute the file through the command prompt. 

`C:\Users\USER1>C:\Users\USER1\Desktop\EDx52Display\EDx52display.exe
2021/05/18 12:20:34 open ./names/commodity.csv: The system cannot find the path specified.
panic: open ./names/commodity.csv: The system cannot find the path specified.`
>
>
`goroutine 1 [running]:
log.Panicln(0xc000077dc8, 0x1, 0x1)
        C:/Go/src/log/log.go:340 +0xc7
github.com/peterbn/EDx52display/edreader.readCsvFile(0x7e4f11, 0x15, 0x0, 0x0, 0x0)
        e:/go/src/github.com/peterbn/EDx52display/edreader/cargo.go:107 +0xba
github.com/peterbn/EDx52display/edreader.initNameMap()
        e:/go/src/github.com/peterbn/EDx52display/edreader/cargo.go:87 +0x41
github.com/peterbn/EDx52display/edreader.init.0()
        e:/go/src/github.com/peterbn/EDx52display/edreader/cargo.go:51 +0x27`

The tool _does_ however generate a mfd.json file containing the correct whereabouts of my character, cargo, star type etcetc.

**Comment by peterbn** [comment]
Hi WaffleGod,

Thank you.

Can you try to download the latest version (https://github.com/peterbn/EDx52display/releases/download/v1.2/Release.zip) and see if that solves the problem?

If you are already using the latest version, can you check if there is a folder named `names` next to the EDx52Display.exe file and whether or not it contains two csv files?

**Comment by WafffleGod** [comment]
Thanks for the fast response on this, much appreciated!

Running the latest version,
In the `names` folder i have `commodity.csv` and `rare_commodity.csv`.

**Comment by peterbn** [comment]
Ok, thank you.

What version of Windows are you on?

**Comment by WafffleGod** [comment]
Win10, latest update i'd assume.

**Comment by peterbn** [comment]
Hi WaffleGod,

I considered your error again, and I realised that it's most likely happening because you weren't running the executable from the directory where it's located (yeah, my code isn't too resilient).

Could you try to 
1) Open the command prompt
2) Navigate to the folder where The EDx52Display.exe file is located
3) Run it directly from there

And then send me any error messages it spits out.

**Comment by WafffleGod** [comment]
Alright, this is what i tried before the servers went down.

I did a full "re-install" of the tool, in case i had some corrupt file laying around.

I tried opening it both with `cd [filepath]` > `start EDx52display.exe` - and I also tried to drag n' drop the file directly from the directory of which it is located straight in to the `cmd`. Both ways will execute the file but all that shows up is a blank command promt (with the .exe file path as the name of the program) that is "read-to only", leaving me with 2 instances of `cmd` with no errors, and no information showing on the MFD. 
![cmd_mfdtool__](https://user-images.githubusercontent.com/84351149/118807366-7c0a5300-b8a8-11eb-9430-d02cedd77a5e.jpg)

The `The system cannot find the path specified.` error is gone.

Does not seem to create a .json file after i re-downloaded and unzipped the fresh verison.

I will try again when the servers go live after the update. Any specific order i should start the tool/game? Or should the tool be working even without the game in the background?

**Comment by peterbn** [comment]
Hi,

Well, one step closer. It only works when you are logged in. Try leaving it running as you start the game, or start it after you've logged in. Both should work.

btw, instead of using `start EDx52Display.exe`, you should be able to run it simply by typing `EDx52Display.exe` when you are in the correct folder. That way, it should start in the same directory.

It should also be printing a message to say that it's running, and that you can press Enter to close it.

**Comment by WafffleGod** [comment]
Hi!

Still getting the blank window, no message saying that it's running, and that I can press Enter to close it. I tried every way i tried before, and how you explained above gave me the same outcome. 

Must be something off with my system.

**Comment by peterbn** [comment]
Sorry to hear that.

If you are interested, I can update the tool with a bunch of extra output logging and we can try to figure out where it's stuck.

**Comment by WafffleGod** [comment]
Wow! Yea that'd super nice. If it's not too much of a hassle for you?

**Comment by peterbn** [comment]
Not really, no - check out https://github.com/peterbn/EDx52display/releases/tag/v1.3

Run the new version with `EDx52display.exe --log=debug` to get more log output. Hopefully that will tell me where it gets stuck. 

I really appreciate your willingness to help me test this by the way.

**Comment by yukinexus** [comment]
I seem to be having the same problem. Keeps getting stuck on "Initializing device driver"

**Comment by cvk77** [comment]
Same here. Stuck on "Initializing device driver"

**Comment by cvk77** [comment]
```
> .\EDx52display.exe --log=debug
DEBUG: Loading configuration...
DEBUG: Configuration loaded.
INFO: Initializing device driver...
DEBUG: Initializing driver connection
```

Then nothing happens.

**Comment by peterbn** [comment]
Hi @yukinexus and @cvk77 

Thank you for your feedback. 
Unfortunately, if the program hangs at `DEBUG: Initializing driver connection`, then the problem lies in the driver, and not in my code. And, since it's working on my end, I don't really have any opportunity to troubleshoot it locally.

Could you ensure that you have the logitech drivers installed, and that you are using an X52 *Pro*, as the software is not intended to work with the non-pro X52.

Regards

**Comment by cvk77** [comment]
@peterbn I just double-checked that I have the correct drivers installed and while the X52 software shows up as x52 pro, the driver was indeed the wrong one. Thanks!

**Comment by peterbn** [comment]
@cvk77 That's good to hear. I'm assuming that it solved your problem?

**Comment by cvk77** [comment]
Yes, everything works fine now

**Comment by vatsdemb-web** [comment]
Don't know if you still reading this but what exact drivers i should use cause i got this  INFO: Initializing device driver...

**Comment by peterbn** [comment]
Hi - I am no longer maintaining this project, as I haven't played Elite for a while now.

You need to use the Logitech drivers for the X52 Pro. You most likely have them installed already if your HOTAS set is working with the game.

That said, it also appears that the game itself has changed where it writes information, so it may not work even if it can talk to the driver.
